/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mingchi.li' at '11/09/17 2:45 PM' with Gradle 2.12
 *
 * @author mingchi.li, @date 11/09/17 2:45 PM
 */

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
